In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender review education purchased
38   45  Female   Good    School        No
22   18  Female   Poor        PG       Yes
11   74    Male   Good        UG       Yes
17   22  Female   Poor        UG       Yes
41   23    Male   Good        PG       Yes

ORDINAL AND LABEL ENCODING

In [2]:
df = df.iloc[:,2:]

In [3]:
df

review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
X_train

review education
32  Average        UG
38     Good    School
15     Poor        UG
20  Average    School
31     Poor    School
5   Average    School
1      Poor        UG
37  Average        PG
49     Good        UG
3      Good        PG
40     Good    School
13  Average    School
47     Good        PG
43     Poor        PG
44  Average        UG
8   Average        UG
41     Good        PG
9      Good        UG
7      Poor    School
16     Poor        UG
34  Average    School
24  Average        PG
33     Good        PG
27     Poor        PG
17     Poor        UG
36     Good        UG
23     Good    School
45     Poor        PG
0   Average    School
19     Poor        PG
18     Good    School
48     Good        UG
4   Average        UG
30  Average        UG
10     Good        UG
11     Good        UG
26     Poor        PG
29  Average        UG
14     Poor        PG
22     Poor        PG

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X_train

array([[1., 1.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.]])

In [18]:
X_test = oe.transform(X_test)

In [19]:
X_test

array([[0., 2.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [0., 2.]])

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [21]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [22]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [23]:
y_train

array([1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1])

ONE- HOT ENCODING

In [25]:
import numpy as np
import pandas as pd
df = pd.read_csv('cars.csv')

In [26]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [27]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [28]:
df['brand'].nunique()

32

ONE HOT ENCODING USING PANDAS

In [29]:
pd.get_dummies(df,columns=['fuel','owner'])

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000     False         True     False   
1       Skoda     120000         370000     False         True     False   
2       Honda     140000         158000     False        False     False   
3     Hyundai     127000         225000     False         True     False   
4      Maruti     120000         130000     False        False     False   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000     False        False     False   
8124  Hyundai     119000         135000     False         True     False   
8125   Maruti     120000         382000     False         True     False   
8126     Tata      25000         290000     False         True     False   
8127     Tata      25000         290000     False         True     False   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0           False               True                       False   
1           False              False                       False   
2            True              False                       False   
3           False               True                       False   
4            True               True                       False   
...           ...                ...                         ...   
8123         True               True                       False   
8124        False              False                        True   
8125        False               True                       False   
8126        False               True                       False   
8127        False               True                       False   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                  False                 False              False  
1                   True                 False              False  
2                  False                 False               True  
3                  False                 False              False  
4                  False                 False              False  
...                  ...                   ...                ...  
8123               False                 False              False  
8124               False                 False              False  
8125               False                 False              False  
8126               False                 False              False  
8127               False                 False              False  

[8128 rows x 12 columns]

K-1 One hot encoding

In [30]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000         True     False        False   
1       Skoda     120000         370000         True     False        False   
2       Honda     140000         158000        False     False         True   
3     Hyundai     127000         225000         True     False        False   
4      Maruti     120000         130000        False     False         True   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000        False     False         True   
8124  Hyundai     119000         135000         True     False        False   
8125   Maruti     120000         382000         True     False        False   
8126     Tata      25000         290000         True     False        False   
8127     Tata      25000         290000         True     False        False   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                          False               False                 False   
1                          False                True                 False   
2                          False               False                 False   
3                          False               False                 False   
4                          False               False                 False   
...                          ...                 ...                   ...   
8123                       False               False                 False   
8124                        True               False                 False   
8125                       False               False                 False   
8126                       False               False                 False   
8127                       False               False                 False   

      owner_Third Owner  
0                 False  
1                 False  
2                  True  
3                 False  
4                 False  
...                 ...  
8123              False  
8124              False  
8125              False  
8126              False  
8127              False  

[8128 rows x 10 columns]

one hot encoding using sklearn

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)
X_train.head()

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [33]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_test_new = ohe.transform(X_test[['fuel','owner']])
X_train_new.shape

(6502, 7)

In [35]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new.toarray()))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

ONE HOT ENCODING WITH TOP CATEGORIES

In [36]:
counts = df['brand'].value_counts()
df['brand'].nunique()
threshold = 100
repl = counts[counts <= threshold].index


BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
1231  False      False  False  False     True     False   False    False   
6492  False      False  False  False    False     False    True    False   
6138  False      False  False  False    False     False   False    False   
2850  False      False  False  False     True     False   False    False   
1596  False      False  False  False    False     False    True    False   

      Skoda   Tata  Toyota  Volkswagen  uncommon  
1231  False  False   False       False     False  
6492  False  False   False       False     False  
6138  False   True   False       False     False  
2850  False  False   False       False     False  
1596  False  False   False       False     False

In [37]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
144   False      False  False  False    False     False   False    False   
4261  False      False  False  False    False     False    True    False   
3353  False      False  False  False    False     False   False     True   
2093  False      False  False  False    False     False    True    False   
6280  False      False  False  False    False     False    True    False   

      Skoda   Tata  Toyota  Volkswagen  uncommon  
144   False  False    True       False     False  
4261  False  False   False       False     False  
3353  False  False   False       False     False  
2093  False  False   False       False     False  
6280  False  False   False       False     False